version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU

branches:
  only:
  - master

skip_tags: true

install:
- cmd: dotnet restore

build:
  project: NReco.LambdaParser.Portable.sln
  verbosity: minimal

build_script:
- cmd: nuget restore src\NReco.LambdaParser.Portable.sln

test_script:
- cmd: nunit-console src\NReco.LambdaParser.Tests\bin\Release\NReco.LambdaParser.Tests.dll